### ISSUE TITLE
Full UI reload triggered periodically by `RangeError: Maximum call stack size exceeded`

### ISSUE THREAD

**Issue by dgolovin** [podman-desktop/podman-desktop#6663]
### Bug description

Monitoring resources with infinite recursive calls eventually triggers the RangeError exception, which triggers reload for current page and probably main thread restart (unconfirmed).

To find out suspects see steps to replicate below \\/ (first suspect is in extensions/podman/src/extension.ts).

### Operating system

macOS M1 Sonoma 14.3

### Installation Method

Other

### Version

next (development version)

### Steps to reproduce

It manifests itself when podman desktop is running long enough and multiple extensions, like podman, container-registry and others alike are active. The reason is the pattern used to monitor certain resources:

```
function monitorFunction() {
   // do monitoring steps
  await new Promise(resolve => setTimeout(resolve, timeoutInMilliseconds);
  monitorFunction();
}
``` 

There is recursive monitorFunction call and it fills up stack if it runs long enough.

If all the patterns like above found and `timeoutInMilliseconds` removed the problem manifests itself much faster by reloading current page. You can set up the break point on mount() function for any svelte component on current page and break point is hit periodically which indicates page reload.

There is also another pattern that should be fine to use, because it is not making recursive call.

```
function monitorFunction(params) {
   // do monitoring steps
  setTimeout(() => monitorFunction(params), timeoutInMilliseconds);
}
```

or

```
function monitorFunction() {
   // do monitoring steps
  setTimeout(monitorFunction, timeoutInMilliseconds);
}
``` 

### Relevant log output

```shell
RangeError: Maximum call stack size exceeded
    at monitorProvider (/Users/eskimo/Sources/podman-desktop/extensions/podman/dist/extension.cjs:5176:1)
    at monitorProvider (/Users/eskimo/Sources/podman-desktop/extensions/podman/dist/extension.cjs:5173:3)
    at monitorProvider (/Users/eskimo/Sources/podman-desktop/extensions/podman/dist/extension.cjs:5173:3)
    at monitorProvider (/Users/eskimo/Sources/podman-desktop/extensions/podman/dist/extension.cjs:5173:3)
    at monitorProvider (/Users/eskimo/Sources/podman-desktop/extensions/podman/dist/extension.cjs:5173:3)
    at monitorProvider (/Users/eskimo/Sources/podman-desktop/extensions/podman/dist/extension.cjs:5173:3)
    at monitorProvider (/Users/eskimo/Sources/podman-desktop/extensions/podman/dist/extension.cjs:5173:3)
    at monitorProvider (/Users/eskimo/Sources/podman-desktop/extensions/podman/dist/extension.cjs:5173:3)
    at monitorProvider (/Users/eskimo/Sources/podman-desktop/extensions/podman/dist/extension.cjs:5173:3)
    at monitorProvider (/Users/eskimo/Sources/podman-desktop/extensions/podman/dist/extension.cjs:5173:3)
    at monitorProvider (/Users/eskimo/Sources/podman-desktop/extensions/podman/dist/extension.cjs:5173:3)
    at monitorProvider (/Users/eskimo/Sources/podman-desktop/extensions/podman/dist/extension.cjs:5173:3)
    at monitorProvider (/Users/eskimo/Sources/podman-desktop/extensions/podman/dist/extension.cjs:5173:3)
    at monitorProvider (/Users/eskimo/Sources/podman-desktop/extensions/podman/dist/extension.cjs:5173:3)
    at monitorProvider (/Users/eskimo/Sources/podman-desktop/extensions/podman/dist/extension.cjs:5173:3)
    at monitorProvider (/Users/eskimo/Sources/podman-desktop/extensions/podman/dist/extension.cjs:5173:3)
    at monitorProvider (/Users/eskimo/Sources/podman-desktop/extensions/podman/dist/extension.cjs:5173:3)
    at monitorProvider (/Users/eskimo/Sources/podman-desktop/extensions/podman/dist/extension.cjs:5173:3)
    at monitorProvider (/Users/eskimo/Sources/podman-desktop/extensions/podman/dist/extension.cjs:5173:3)
    at monitorProvider (/Users/eskimo/Sources/podman-desktop/extensions/podman/dist/extension.cjs:5173:3)
    at monitorProvider (/Users/eskimo/Sources/podman-desktop/extensions/podman/dist/extension.cjs:5173:3)
    at monitorProvider (/Users/eskimo/Sources/podman-desktop/extensions/podman/dist/extension.cjs:5173:3)
```

### Additional context

Sack size limit in nodejs is around 1MiB if there are multiple monitoring functions executed using recursion pattern they eventually will eat all the memory up to the limit.

**Comment by dgolovin** [comment]
This is still an issue.

**Comment by dgolovin** [comment]
The call is still recursive and I see UI resetting itself if I am waiting long enough.

**Comment by dgolovin** [comment]
I still can replicate it.
